name: Deploy FastAPI app

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      app_dir:
        required: true
        type: string
      alembic_migrate:
        required: false
        type: string
        default: "false"
      lxc_user:
        required: true
        type: string
    secrets:
      LXC_HOST:
        required: true
      ENV_FILE:
        required: true
      GH_RUNNER_KEY:
        required: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout cicd repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/cicd
          path: .cicd

      - name: Checkout app code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: ./app

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GH_RUNNER_KEY }}

      - name: Add LXC host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.LXC_HOST }} >> ~/.ssh/known_hosts

      - name: Copy .env (if exists)
        if: ${{ secrets.ENV_FILE != '' }}
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          rsync -avz .env ${{ inputs.lxc_user }}@${{ secrets.LXC_HOST }}:${{ inputs.app_dir }}/.env
          rm .env

      - name: Rsync app files
        run: |
          rsync -avz --delete \
            --exclude '.git*' \
            --exclude '.github*' \
            --exclude '.cicd' \
            --exclude '.venv' \
            --exclude '__pycache__' \
            ./app/ ${{ inputs.lxc_user }}@${{ secrets.LXC_HOST }}:${{ inputs.app_dir }}

      - name: Execute deploy script
        run: |
          ssh ${{ inputs.lxc_user }}@${{ secrets.LXC_HOST }} \
          "cd ${{ inputs.app_dir }} && \
           SERVICE_NAME='${{ inputs.service_name }}' \
           ALEMBIC_MIGRATE='${{ inputs.alembic_migrate }}' \
           bash .cicd/scripts/deploy-fastapi.sh"
